version: "3"
services:
  mongo:
    build: 
      context: .
      dockerfile: docker/mongo/Dockerfile
    environment:
      - MONGODB_DATABASE=stage
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - backend
  node:
    build: 
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/stage
      - PORT=4000
      - GRAPHQL_PORT=4001
      - SECRET_KEY='asdf123456'
      - UNSPLASH_AK='-yOmcLwpqRYd_3vR_P6Wgi210BbR_jOi_VefToBqDYU'
      - UNSPLASH_SK='m_-8KByljD0OYY9PzTgiHHE3MmfQ6F4N_x41w0PDt8g'
      - PIXABAY_AK='19213825-ebec08c3546ba09000a38f84f'
      - STORYBLOCKS_PK='test_f8eecc0879b845b0cc485363e92f6c342b6dfe4fd740c52022c624b4845'
      - STORYBLOCKS_PRK='test_655a5d66a8b3a234bf67a8edece6d9dfe9ea116ba7e4161c228d72a7b81'
    entrypoint: /entrypoint.sh -d mongo:27017 -c 'yarn start';
    networks:
      - backend
networks:
  backend:
volumes:
  mongodata: 